### PR TITLE
Perform and document manual testing

### PR DESCRIPTION
**Pull request by biroferenc075**

### CODE REVIEW

**Review by szaboegon — CHANGES_REQUESTED** [review]
Please write a short summary about your task in the 'doc' folder. See template on other branches. Otherwise very nice work, tests are easy to read.

**Comment by gerinagy10** [comment]
I made the summary you mentioned. The pull request can be merged into the main branch.

**Review by szaboegon — APPROVED** [review]
Looks good. Nice work!

**Comment by szaboegon** [comment]
Solved merge conflicts. Merging into main.

**Pull request merged**
